require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '15.1'

setup_permissions([
  'Microphone',
  'LocationWhenInUse'
])

# Disable New Architecture completely - must be set BEFORE prepare_react_native_project
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

prepare_react_native_project!

target 'voiceanalyzermobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Align every pod with our minimum iOS version (15.1)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        
        # Explicitly disable New Architecture for ALL pods
        config.build_settings.delete('RCT_NEW_ARCH_ENABLED')
        config.build_settings['RCT_NEW_ARCH_ENABLED'] = '0'
      end
      
      # Fix for Hermes build script missing REACT_NATIVE_PATH
      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          config.build_settings['REACT_NATIVE_PATH'] = "${PODS_ROOT}/../node_modules/react-native"
        end
      end

      # Ensure @react-native-community/slider never pulls Fabric sources
      next unless target.name == 'react-native-slider'
      next unless target.respond_to?(:subspecs)

      target.subspecs.each do |subspec|
        next unless subspec.name&.end_with?('Fabric')
        subspec.remove_from_project
      end
    end
  end
end
